name: notepadqq 
version: '2.0.0-beta+git'
summary: A Notepad++-like editor for Linux.
description: |
  It helps developers by providing all you can expect from a general purpose text editor, such as syntax highlighting for more than 100 different languages, code folding, color schemes, file monitoring, multiple selection and much more.
  You can search text using the power of regular expressions. You can organize documents side by side. You can use real-time highlighting to find near identifiers in no time.
grade: stable
confinement: classic
icon: support_files/icons/hicolor/scalable/apps/notepadqq.svg
base: core22

apps:
  notepadqq: 
    command: bin/desktop-launch $SNAP/usr/local/lib/notepadqq/notepadqq-bin
    environment:
      DISABLE_WAYLAND: 1  # See https://github.com/notepadqq/notepadqq/issues/806
    desktop: usr/local/share/applications/notepadqq.desktop
#   plugs:  # Plugs are not needed for classic confinement
#     - browser-support
#     - desktop
#     - desktop-legacy
#     - gsettings
#     - home
#     - media-hub
#     - network-bind
#     - network-manager
#     - opengl
#     - optical-drive
#     - removable-media
#     - unity7
#     - x11

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qt6-base-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - xdg-user-dirs

  fixicon:
    plugin: nil
    after: [my-part]
    override-build: |
      sed -i 's|Icon=notepadqq|Icon=/usr/local/share/icons/hicolor/scalable/apps/notepadqq\.svg|' $SNAPCRAFT_STAGE/usr/local/share/applications/notepadqq.desktop

  qtconf:
    plugin: dump
    source: snap/local
    organize:
      qt.conf: usr/local/lib/notepadqq/qt.conf
      qt.WebEngineProcess.conf: usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/libexec/qt.conf
    override-build: |
      sed -i "s|__ARCH_TRIPLET__|$SNAPCRAFT_ARCH_TRIPLET|" qt.conf qt.WebEngineProcess.conf
      snapcraftctl build
    after: [my-part]

  my-part:
    build-packages:
      - cmake
      - pkg-config
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - qt6-l10n-tools
      - libqt6websockets6-dev
      - libqt6svg6-dev
      - libqt6core5compat6-dev
      - libqt6webchannel6-dev
      - libqt6opengl6-dev
      - libuchardet-dev
      - libgl1-mesa-dev
    stage-packages: 
      - adwaita-icon-theme-full
      - coreutils
      - desktop-file-utils
      - hicolor-icon-theme
      - libatk-adaptor
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libnss3
      - libuchardet0
      
    source: . 
    after: [desktop-qt5]
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DCMAKE_BUILD_TYPE=Release
